version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  test-gen:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Debug Environment
          command: |
            echo "GH_TOKEN is set: ${GH_TOKEN:+true}"  # Just checks presence, doesn't leak token
            echo "CIRCLE_PULL_REQUEST_NUMBER: $CIRCLE_PULL_REQUEST_NUMBER"
      - run:
          name: Run Test Generator
          command: |
            node test-generator/generate-tests.js archanaknayanar job-portal $CIRCLE_PULL_REQUEST_NUMBER https://fortuneindia-rpsg-web.qtstage.io/
      - persist_to_workspace:
          root: .
          paths:
            - playwright/tests
            - playwright/scenario-txt

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: Run Tests
          command: npx playwright test
      - store_artifacts:
          path: playwright/scenario-txt
          destination: scenario-txt
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test-gen-workflow:
    jobs:
      - test-gen:
          filters:
            branches:
              only: /.*test-gen.*/
      - run-tests:
          requires:
            - test-gen
